### ISSUE TITLE
🎉 I'd love to see more

### ISSUE THREAD

**Issue by abh** [jjatria/perl-opentelemetry#1]
I don't have time to help, but I'd love to see more of this work to use in my Perl based projects (specifically in the Perl code on https://www.ntppool.org/ to integrate diagnostics and tracing better with the Go based services).

**Comment by jjatria** [comment]
Thanks for the feedback! I keep getting distracted away from this, but I do hope to be able to get back into it sooner rather than later :muscle:

**Comment by kylemhall** [comment]
I am also watching your work with excitement. I'd love to add telemetry to https://koha-community.org/ and https://libki.org
