### ISSUE TITLE
Tests failing with Feature::Compat::Try 0.04

### ISSUE THREAD

**Issue by andk** [jjatria/perl-opentelemetry#11]
Sample fail report: http://www.cpantesters.org/cpan/report/1dc24380-914e-11ee-a2cf-3ab28d29d093

Bumping the dependency declaration to 0.05 should do

**Comment by jjatria** [comment]
Thanks for the report! I'll push a change and a new release later today

**Comment by jjatria** [comment]
This should be fixed with OpenTelemetry 0.19, now on CPAN. Thanks!
