### ISSUE TITLE
LWP::UserAgent simple_request not instrumented

### ISSUE THREAD

**Issue by marrem** [jjatria/perl-opentelemetry#13]
I found out using `REST::Client` that no headers were propagated by `LWP::UserAgent`. 

Debugging I found out that `REST::Client` used `LWP::UserAgent->simple_request` instead of `->request`

Is it possible to add changing the simple_request as well to the install method. Or maybe change simple_request instead of request, since the latter uses the former.

**Comment by jjatria** [comment]
Interesting. Well spotted. I think the main issue here would be that [we are expected to count retries](https://github.com/jjatria/perl-opentelemetry/blob/ff4e4e6d2142e1d45f829bda04948f88f0467ca6/lib/OpenTelemetry/Integration/LWP/UserAgent.pm#L122-L125), and `simple_request` does not handle those: those are handled a level above, in `request`.

We are definitely going to have to instrument `simple_request`, but we'll need to be careful to not count things twice. I'll try to take a look at this soon. It might not be as hard as I'm imagining.

**Comment by jjatria** [comment]
I've pushed a fix for this on 0ca2339. I'll mint a new release shortly which will include this and should fix this issue.

**Comment by jjatria** [comment]
OpenTelemetry 0.020 has been released to CPAN with this change. It should be indexed shortly.
