### ISSUE TITLE
When LWP integration sends an error it puts an integer in the status description that is required to be a string.

### ISSUE THREAD

**Issue by tj-cisco** [jjatria/perl-opentelemetry#15]
Fixed in #14.

When sending data through otel-collector it generates a 400 error when trying to parse the status description.

**Comment by jjatria** [comment]
Thanks for the report!

I fee like this is an issue at the exporter level: the exporter should know to send the data in the correct format, regardless of what the integrations put in.

Are you using the JSON exporter? I think the protobuf exporter should be converting this to a string anyway, but the JSON one I don't think is giving doing anything about types (so there may be other fields we want to coerce).

**Comment by tj-cisco** [comment]
Yes this is the JSON exporter, this 'fix' forces the issue but your probably right the real bug is in the json exporter.

**Comment by jjatria** [comment]
If that's the case, I _think_ this might be what is needed: https://github.com/jjatria/perl-opentelemetry-exporter-otlp/commit/6ffd710a6ea96a68f2ccd3aebb94ed21f1afa5f7

If you are able to check this works on your end, then I can mint a release and push to CPAN. If not... well, I guess I can still push to CPAN. :sweat_smile: 

I'll release before tomorrow morning.

**Comment by jjatria** [comment]
I just pushed [version 0.016 of OpenTelemetry::Exporter::OTLP](https://metacpan.org/release/JJATRIA/OpenTelemetry-Exporter-OTLP-0.016), which contains this change. It should be indexed to CPAN shortly.

Please let me know if it solves your issue, so we can close this. And thanks again for raising it!

**Comment by jjatria** [comment]
Closing this since this issue seems to have been resolved.
