### ISSUE TITLE
Typo in OpenTelemetry::Integration::DBI

### ISSUE THREAD

**Issue by uid66** [jjatria/perl-opentelemetry#17]
Please correct `$DO = \&DBI::st::execute;` to `$DO = \&DBI::db::do;` in [line](https://github.com/jjatria/perl-opentelemetry/blob/998c1167c6f2089ea8ea3cd5f0da319772e3a917/lib/OpenTelemetry/Integration/DBI.pm#L113)

**Comment by jjatria** [comment]
Oh, well spotted. Thanks! This was fixed in c459e90 and that should be going out to CPAN shortly.

**Comment by jjatria** [comment]
This change went out with OpenTelemetry 0.023.
