### ISSUE TITLE
version definitions in OpenTelemetry::Baggage packages incorrect

### ISSUE THREAD

**Issue by abraxxa** [jjatria/perl-opentelemetry#18]
cpan-outdated-coro lists the OpenTelemetry::Baggage as updatable all the time because two or the three packages in Baggage.pm will have version 0.010.

**Comment by jjatria** [comment]
Oh, interesting. I guess the version bumping step in my Dist::Zilla setup is not prepared to find several versions in a single file. It looks like setting [the `global` option for the RewriteVersion plugin](https://metacpan.org/pod/Dist::Zilla::Plugin::RewriteVersion#global) should fix this.
