### ISSUE TITLE
problem with installing dependencies

### ISSUE THREAD

**Issue by margec** [jjatria/perl-opentelemetry#2]
this is more like a question than issue.

i am inside a Docker container running base image 'centos:7', with perl v5.26.3 installed, and trying to install this, but it has these dependencies:

Object::Pad
XS::Parse::Sublike::Builder

and i am stuck at installing XS::Parse::Sublike::Builder which was down to compiling some C code, apologies for asking amateur question, but can someone tell me how to pass option -std=c99 to that cc statement in order to be able to finish installing XS::Parse::Sublike::Builder please?

`
[root@9aa82d4595a3 perl-opentelemetry]# cpanm XS::Parse::Sublike::Builder
--> Working on XS::Parse::Sublike::Builder
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/XS-Parse-Sublike-0.17.tar.gz ... OK
Configuring XS-Parse-Sublike-0.17 ... OK
Building and testing XS-Parse-Sublike-0.17 ... FAIL
! Installing XS::Parse::Sublike::Builder failed. See /root/.cpanm/work/1686690777.2743/build.log for details. Retry with --force to force install it.
[root@9aa82d4595a3 perl-opentelemetry]# cat /root/.cpanm/work/1686690777.2743/build.log
cpanm (App::cpanminus) 1.7046 on perl 5.026003 built for aarch64-linux
Work directory is /root/.cpanm/work/1686690777.2743
You have make /usr/bin/make
You have /usr/bin/wget
You have /usr/bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Searching XS::Parse::Sublike::Builder () on cpanmetadb ...
--> Working on XS::Parse::Sublike::Builder
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/XS-Parse-Sublike-0.17.tar.gz
-> OK
Unpacking XS-Parse-Sublike-0.17.tar.gz
Entering XS-Parse-Sublike-0.17
Checking configure dependencies from META.json
Checking if you have Module::Build 0.4004 ... Yes (0.4234)
Checking if you have ExtUtils::Install 1.46 ... Yes (2.04)
Configuring XS-Parse-Sublike-0.17
Running Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'XS-Parse-Sublike' version '0.17'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Sub::Util 0 ... Yes (1.46_02)
Checking if you have Test::Fatal 0 ... Yes (0.017)
Checking if you have Test::More 0.88 ... Yes (1.302195)
Checking if you have ExtUtils::CBuilder 0 ... Yes (0.280225)
Building and testing XS-Parse-Sublike-0.17
Building XS-Parse-Sublike
cc -I/root/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/aarch64-linux/CORE -DVERSION="0.17" -DXS_VERSION="0.17" -fPIC -I. -Ihax -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o lib/XS/Parse/Sublike.o lib/XS/Parse/Sublike.c
In file included from lib/XS/Parse/Sublike.xs:36:0:
hax/parse_subsignature.c.inc: In function 'S_parse_subsignature':
hax/parse_subsignature.c.inc:412:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for(OP *o = namedelems; o; o = OpSIBLING(o)) {
     ^
hax/parse_subsignature.c.inc:412:5: note: use option -std=c99 or -std=gnu99 to compile your code
error building lib/XS/Parse/Sublike.o from 'lib/XS/Parse/Sublike.c' at /root/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/ExtUtils/CBuilder/Base.pm line 174.
-> FAIL Installing XS::Parse::Sublike::Builder failed. See /root/.cpanm/work/1686690777.2743/build.log for details. Retry with --force to force install it.
[root@9aa82d4595a3 perl-opentelemetry]
`

**Comment by leonerd** [comment]
Ah oops. That should be handled by the `Build.PL` for those older perls before the Perl build system put it there anyway, but it seems I forgot that.

As a quick workaround hack you can add

```perl
push @extra_compiler_flags, qw( -std=c99 );
```

into Build.PL just after line 9, where it sets up the other flags anyway. That should at least let it build.

**Comment by leonerd** [comment]
There's now a new version on CPAN (https://metacpan.org/release/PEVANS/XS-Parse-Sublike-0.18) which should fix this.

**Comment by margec** [comment]
much appreciated @leonerd! installing XS-Parse-Sublike-0.18 has allowed me to proceed.

now i have run into 2 complaints about 'Unescaped left brace' at TraceState.pm, at lines 26 and 33.

`
[root@753a5a531293 app]# perlbrew list-modules|grep Open
OpenTelemetry
OpenTracing
OpenTracing::GlobalTracer
OpenTracing::Interface
Test::OpenTracing::Interface
[root@753a5a531293 app]#
[root@753a5a531293 app]# cat test.pl
use warnings;
use strict;

use feature "say";

use OpenTelemetry;

#############################

say "hello world from test.pl!";

#################################

__END__
[root@753a5a531293 app]# perl test.pl
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/
        ^
        (?:
                [ a-z ]     [ a-z 0-9 _ * / - ]{ <-- HERE ,255} # simple-key
            | (?:                                      # multi-tenant-key
                [ a-z 0-9 ] [ a-z 0-9 _ * / - ]{,240} #   tenant-id
                @
                [ a-z ]     [ a-z 0-9 _ * / - ]{,13}  #   system-id
              )
        )
        $
    / at /root/perl5/lib/perl5/OpenTelemetry/Propagator/TraceContext/TraceState.pm line 26.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/
        ^
        (?:
                [ a-z ]     [ a-z 0-9 _ * / - ]{,255} # simple-key
            | (?:                                      # multi-tenant-key
                [ a-z 0-9 ] [ a-z 0-9 _ * / - ]{ <-- HERE ,240} #   tenant-id
                @
                [ a-z ]     [ a-z 0-9 _ * / - ]{,13}  #   system-id
              )
        )
        $
    / at /root/perl5/lib/perl5/OpenTelemetry/Propagator/TraceContext/TraceState.pm line 26.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/
        ^
        (?:
                [ a-z ]     [ a-z 0-9 _ * / - ]{,255} # simple-key
            | (?:                                      # multi-tenant-key
                [ a-z 0-9 ] [ a-z 0-9 _ * / - ]{,240} #   tenant-id
                @
                [ a-z ]     [ a-z 0-9 _ * / - ]{ <-- HERE ,13}  #   system-id
              )
        )
        $
    / at /root/perl5/lib/perl5/OpenTelemetry/Propagator/TraceContext/TraceState.pm line 26.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/
        ^
            [ \x{20} \x{21}-\x{2B} \x{2D}-\x{3C} \x{3E}-\x{7E} ]{ <-- HERE ,255}
            [        \x{21}-\x{2B} \x{2D}-\x{3C} \x{3E}-\x{7E} ]
        $
    / at /root/perl5/lib/perl5/OpenTelemetry/Propagator/TraceContext/TraceState.pm line 33.
hello world from test.pl!
[root@753a5a531293 app]#
`

**Comment by margec** [comment]
upgrading to Perl v5.36.1 did the trick, thanks and feel free to close this.

**Comment by jjatria** [comment]
Glad you got this working! I should investigate those brackets, because it might be that I need to bump the minimum Perl version a little :thinking:

**Comment by jjatria** [comment]
Yeah, looks like the current minimum Perl is 5.33.6, because of that file:
```
$ perlver lib/OpenTelemetry/Propagator/TraceContext/TraceState.pm


   ---------------------------------------------------------------------------------------  
 | file                                                    | explicit | syntax  | external |
 | --------------------------------------------------------------------------------------- |
 | lib/OpenTelemetry/Propagator/TraceContext/TraceState.pm | ~        | v5.33.6 | n/a      |
 | --------------------------------------------------------------------------------------- |
 | Minimum explicit version : ~                                                            |
 | Minimum syntax version   : v5.33.6                                                      |
 | Minimum version of perl  : v5.33.6                                                      |
   ---------------------------------------------------------------------------------------  


```
I've added a missing META file with this requirement.
