### ISSUE TITLE
Forward trace to grafana / tempo?

### ISSUE THREAD

**Issue by jegade** [jjatria/perl-opentelemetry#4]
Hi, i'm new to opentelemetry - how could i output/access the trace after the process is done? 

I would like to forward the data to e.g. Grafana Tempo so that we can analyse it there. At the moment, however, I am having trouble with the output or access to the trace. 

Best regards,
Jens

**Comment by jjatria** [comment]
Thank you for the interest in this project, but it looks like your question might be better asked in a different venue. This project is mostly concerned with how to generate OpenTelemetry data from an application written in Perl, but your question is more to do with what to do with eg. the traces once you have them.

Looking around, it seems like Grafana Tempo can receive data from the OpenTelemetry collector, as [explained in this blog post](https://grafana.com/blog/2021/04/13/how-to-send-traces-to-grafana-clouds-tempo-service-with-opentelemetry-collector).

Although the code in this repository is still pretty experimental, it should already allow you to send trace data to the OpenTelemetry collector using the (also experimental) [OTLP exporter](https://github.com/jjatria/perl-opentelemetry-exporter-otlp). Assuming your application is using Perl, you can see a demo of these distributions being used together to talk to the OTel collector in [my fork of the OpenTelemetry demo](https://github.com/jjatria/opentelemetry-demo/tree/perl).

I'll close this as it seems off topic, but if you have any other specific questions, please feel free to open a new issue. If your questions are with the configuration of the collector, however, you'll probably be best served by asking them in their support channels.

Hope this helped.
