### ISSUE TITLE
Test is failing if SQL-Statement is installed

### ISSUE THREAD

**Issue by andk** [jjatria/perl-opentelemetry#6]
Two reports from the same perl installation. A pass, then a fail. Between the two reports I installed REHSACK/SQL-Statement-1.414.tar.gz

- pass: http://www.cpantesters.org/cpan/report/62f92108-7dfd-11ee-ab46-c6c348cad472
- fail: http://www.cpantesters.org/cpan/report/c29bbbf2-7dfd-11ee-856d-cbcc48cad472

**Comment by eserte** [comment]
Still same problem in OpenTelemetry-0.015

**Comment by jjatria** [comment]
Thanks for the report! I'll take a look
